name = "Journal"
license = "MIT"
licenselink = "https://github.com/9623-Warp-Drive/hugo-journal/blob/main/LICENSE.md"
description = "Extremely minimal journal-style theme for VRC teams"
homepage = "https://github.com/9623-Warp-Drive/hugo-journal"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Nathan Goller-Deitsch"
  homepage = "https://quartzic.co"
